### PR TITLE
User Flow diagram

### PR DESCRIPTION
**Pull request by dianashk**
@meghanhade made this excellent user flow diagram to help visualize the steps we need to implement as part of this system.

*Note: This is a temporary place to track all the notes on the user flow diagram. We can move the resulting file to a better location or rename if needed.*

### CODE REVIEW

**Comment by dianashk** [comment]
- in `1d` we should have 2 options:
   - select from list of common licenses
   - upload or copy-paste your own license

**Comment by dianashk** [comment]
- consider switching `1f` and `1e` just to keep information about the source together in the flow, should ask @souperneon

**Comment by dianashk** [comment]
- is there a way to capture error condition flows? like what happens in a failure to download the data? or is that just something you take care of inside each of the steps and doesn't generally get called out in such diagrams?

**Comment by dianashk** [comment]
- under maintenance, do we need the `no update available at this time` option?

**Comment by dianashk** [comment]
- after maintenance, there should be a `Submission Verification and Feedback` step as well but perhaps with a different outcome than the submission one

**Comment by dianashk** [comment]
I think those are all my notes for now. 

It looks great overall and is incredibly helpful in visualizing the user experience! 🚀 
The numbers are also helpful in discussing individual parts of the system without having to explain which step you're talking about each time. Being able to say you're working on `1e`, for example, is super convenient. ✨ ✨ ✨

**Comment by souperneon** [comment]
Sweet diagram! Can either of you help me understand this better, by walking me with through it?

**Comment by meghanhade** [comment]
@souperneon I'd be happy to! I'll send a calendar invite.

**Comment by iandees** [comment]
This looks great so far. Two things to think about:

- It'd be useful to specifically decide which of the advanced conform/column mapping functions we want to support. In an initial interface I'd recommend that we only allow mapping things directly without supporting any of the functions.
- I worry a bit about people generating outputs from their GIS specifically for OpenAddresses. One of the important aspects of OA (and hopefully this tool) is that it can work with what people already have and if we decide to add columns in the future we can retroactively make existing sources work. Basically: I want people to feel like they can give us everything they have in whatever format they have and not have to generate an output specifically to match the "OpenAddresses standard". The interface and this flow might be able to help this with carefully placed documentation or notes to the user during the flow.

**Comment by migurski** [comment]
Looks like a great start! I’d love to see @souperneon take a crack at this to generate a similar deliverable to last year’s Mapzen email login flow. That was a very effective presentation of user flow.

I agree with Ian that we'd like for people to be able to offer their data in their own formats. There’s a fair chance that we have enough example conforms now to make a reasonable guess for new uploads.

**Comment by meghanhade** [comment]
Updated user flow document: https://www.lucidchart.com/invitations/accept/348697a9-cb7f-43b8-a95b-c3e482cdd61e

The Mapzen email login flow was the model for this new doc--it's  work in progress, so please feel free to comment/suggest edits.

**Comment by meghanhade** [comment]
I've added a png file of the lucidchart document to the docs directory, it can be found here: 
https://github.com/mapzen/mobility-on-demand-sandbox-contributions/blob/master/docs/user_flow.png

I'll be closing this PR. Please submit any further comments on this doc as new issues. Thanks!

**Pull request closed without merging**
