### PR TITLE
add cancel button

### LINKED ISSUE #79: Review: add cancel button
- will return user to the beginning of the flow

### PR DESCRIPTION
**Pull request by meghanhade**
Adds cancel button that returns user to beginning and clears out submission model.

closes #79

### CODE REVIEW

**Comment by hanbyul-here** [comment]
I see some data are cleared out, but some are not. ex. search keyword still stays there. Is this supposed to clear out only the data part of model?

**Comment by dianashk** [comment]
Feels a bit dangerous to just have that button there without any warnings. Could we add a prompt on-click to let the user know this will take them all the way back to the beginning of the process and erase all of their entries?

**Comment by meghanhade** [comment]
@dianashk yep, you're right. I'm going to add that to a new issue for copy/ui polish.

**Comment by meghanhade** [comment]
@hanbyul-here I switched the license drop down to save the choice to the model, and this fixed the issue where the drop downs were still pre-populated after the cancel. I only changed the license drop down for now, because all others will be changing.

**Pull request merged**
