### PR TITLE
Adding Feed Progress Tabs

### PR DESCRIPTION
**Pull request by mkong0216**
- Currently using {{#link-to}} to add .active class to the <li> element that matches the current route
- Added styling for .active class and changed h1, h2, h3, h4, and h5 to match styleguide in app.css based on issue #56 (not sure if this is how to do it though...)

### CODE REVIEW

**Comment by meghanhade** [comment]
@mkong0216 this is looking good! There is a built-in property on the application controller called `currentRouteName`. You can use this to check what the current route is from the application template: `{{currentRouteName}}`, and set an active class in the template based on that, like this:
```
class={{if (eq currentRouteName 'intro') "active"}}
```
The format for using `if` statements to set a class is different from elsewhere in the templating, where it would be
```
{{#if currentRouteName}}
...
{{/if}}
```
The `eq` in `{{if (eq currentRouteName 'intro') "active"}}` is from [ember-truth-helpers](https://github.com/jmurphyau/ember-truth-helpers). Normally, `{{#if currentRouteName}}` checks for the truthiness of `currentRouteName`, but ember-truth-helpers allows for more nuanced comparisons (like how we're checking if the current route equals 'intro').

**Comment by mkong0216** [comment]
@meghanhade : ahhh thank you! Yea, I wasn't sure how to compare currentRouteName to a value since when I was looking things up it says ember doesn't allow that. So just to clarify, ember-truth-helpers is not a part of ember, it's something you would have to install yourself?

**Comment by meghanhade** [comment]
@mkong0216 Yep! Ember-truth-helpers is an ember addon that has already been installed on this app.

**Comment by mkong0216** [comment]
@meghanhade : mind checking the changes I made and approving PR if everything is okay? 
- Now using `eq` to check `currentRouteName` and adding `.active` class to corresponding tab
- Merged in master
- Updated edit button link for data section and more-info section on Review page. Originally they both redirected to Contact page. Fixed so it now it redirects to the correct pages.

**Pull request merged**
