### PR TITLE
Intro update

### LINKED ISSUE #72: Intro: start flow by pasting URL/uploading file
- backend will validate format
- if file/link isn't approved/recognized by backend, user will be directed to help-needed page

### LINKED ISSUE #78: Review: URL step review shouldn't be editable

### PR DESCRIPTION
**Pull request by meghanhade**
Removes country/region search and changes first step of flow to ask user for a link to the data or to upload a data file. The link to edit this step is removed from the review page, as changing this step would be the same as starting over.

Once the OA backend is ready, it will validate format. If file/link isn't approved/recognized by backend, user will be directed to help-needed page.

Closes #78 and closes #72

### CODE REVIEW

**Comment by hanbyul-here** [comment]
Do we still leave the page asking data type/link to user? or is that page going to be prefilled from backend response? (so it becomes more like a confirmation page?)

**Comment by dianashk** [comment]
We would need to remove the second page since @trescube is able to detect the type of data we're dealing with on the backend.

**Comment by meghanhade** [comment]
@dianashk @hanbyul-here in a meeting with @souperneon and @mkong0216 earlier this week, we decided to move "frequency of update" and "who created the data" (formerly called "source"; @dianashk please let us know if you disagree with this description) to the license information step. For more info on these change, see the photo posted in the project Slack channel. I'll make this change in a separate branch.

**Comment by dianashk** [comment]
That should be fine if you guys don't feel like the license page would get too crowded. The page I was referring to here is the one asking what type of data they have, with the dropdown containing ArcGIS/download/upload.

**Pull request merged**
