### PR TITLE
Edit mode

### PR DESCRIPTION
**Pull request by meghanhade**
Work towards #20 

This adds in UI and functionality to return to steps in the flow from the review step. When finished editing, the model/changeset are updated and you are returned to the review.

### CODE REVIEW

**Comment by hanbyul-here** [comment]
I can see that changes are not going through validations. Is this intended? or you expect me to work on this?

**Comment by meghanhade** [comment]
@hanbyul-here I discussed the edit-mode approach with @dianashk today. A couple of the categories (e.g. "data") will require the user to step back through the whole flow (because it will change fields in other categories as well). I'll mark this PR as in-progress until those changes are made, and the validation is utilized.

**Comment by meghanhade** [comment]
@hanbyul-here could you take a look at validations for this? I believe they should be working now that the `nav-button` is being used as before.

**Comment by hanbyul-here** [comment]
@meghanhade validation is working as expected. I just did tiny edits for styling (put nav buttons into container on mapping page)

**Pull request merged**
